In [2]:
import numpy as np
import pandas as pd
import json
path = 'example.txt'
records = [json.loads(line) for line in open(path)]
records[0]

{'a': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.78 Safari/535.11',
 'c': 'US',
 'nk': 1,
 'tz': 'America/New_York',
 'gr': 'MA',
 'g': 'A6qOVH',
 'h': 'wfLQtf',
 'l': 'orofrog',
 'al': 'en-US,en;q=0.8',
 'hh': '1.usa.gov',
 'r': 'http://www.facebook.com/l/7AQEFzjSi/1.usa.gov/wfLQtf',
 'u': 'http://www.ncbi.nlm.nih.gov/pubmed/22415991',
 't': 1331923247,
 'hc': 1331822918,
 'cy': 'Danvers',
 'll': [42.576698, -70.954903]}

In [3]:
frame = pd.DataFrame(records)
frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3560 entries, 0 to 3559
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   a            3440 non-null   object
 1   c            2919 non-null   object
 2   nk           3440 non-null   float64
 3   tz           3440 non-null   object
 4   gr           2919 non-null   object
 5   g            3440 non-null   object
 6   h            3440 non-null   object
 7   l            3440 non-null   object
 8   al           3094 non-null   object
 9   hh           3440 non-null   object
 10  r            3440 non-null   object
 11  u            3440 non-null   object
 12  t            3440 non-null   float64
 13  hc           3440 non-null   float64
 14  cy           2919 non-null   object
 15  ll           2919 non-null   object
 16  _heartbeat_  120 non-null    float64
 17  kw           93 non-null     object
dtypes: float64(4), object(14)
memory usage: 500.8+ KB

In [5]:
xx= frame.groupby('tz')

In [7]:
xx.describe()

                        nk                                                \
                     count      mean       std  min  25%  50%   75%  max
tz
                     521.0  0.397313  0.489812  0.0  0.0  0.0  1.00  1.0
Africa/Cairo           3.0  0.333333  0.577350  0.0  0.0  0.0  0.50  1.0
Africa/Casablanca      1.0  0.000000       NaN  0.0  0.0  0.0  0.00  0.0
Africa/Ceuta           2.0  0.000000  0.000000  0.0  0.0  0.0  0.00  0.0
Africa/Johannesburg    1.0  0.000000       NaN  0.0  0.0  0.0  0.00  0.0
...                    ...       ...       ...  ...  ...  ...   ...  ...
Europe/Volgograd       1.0  0.000000       NaN  0.0  0.0  0.0  0.00  0.0
Europe/Warsaw         16.0  0.125000  0.341565  0.0  0.0  0.0  0.00  1.0
Europe/Zurich          4.0  0.250000  0.500000  0.0  0.0  0.0  0.25  1.0
Pacific/Auckland      11.0  0.272727  0.467099  0.0  0.0  0.0  0.50  1.0
Pacific/Honolulu      36.0  0.833333  0.377964  0.0  1.0  1.0  1.00  1.0

                         t                ...            hc                \
                     count          mean  ...           75%           max
tz                                        ...
                     521.0  1.331925e+09  ...  1.331916e+09  1.331926e+09
Africa/Cairo           3.0  1.331924e+09  ...  1.331923e+09  1.331923e+09
Africa/Casablanca      1.0  1.331926e+09  ...  1.328021e+09  1.328021e+09
Africa/Ceuta           2.0  1.331925e+09  ...  1.331649e+09  1.331671e+09
Africa/Johannesburg    1.0  1.331925e+09  ...  1.331923e+09  1.331923e+09
...                    ...           ...  ...           ...           ...
Europe/Volgograd       1.0  1.331926e+09  ...  1.331923e+09  1.331923e+09
Europe/Warsaw         16.0  1.331924e+09  ...  1.331923e+09  1.331923e+09
Europe/Zurich          4.0  1.331925e+09  ...  1.331918e+09  1.331923e+09
Pacific/Auckland      11.0  1.331926e+09  ...  1.331908e+09  1.331923e+09
Pacific/Honolulu      36.0  1.331924e+09  ...  1.331923e+09  1.331923e+09

                    _heartbeat_
                          count mean std min 25% 50% 75% max
tz
                            0.0  NaN NaN NaN NaN NaN NaN NaN
Africa/Cairo                0.0  NaN NaN NaN NaN NaN NaN NaN
Africa/Casablanca           0.0  NaN NaN NaN NaN NaN NaN NaN
Africa/Ceuta                0.0  NaN NaN NaN NaN NaN NaN NaN
Africa/Johannesburg         0.0  NaN NaN NaN NaN NaN NaN NaN
...                         ...  ...  ..  ..  ..  ..  ..  ..
Europe/Volgograd            0.0  NaN NaN NaN NaN NaN NaN NaN
Europe/Warsaw               0.0  NaN NaN NaN NaN NaN NaN NaN
Europe/Zurich               0.0  NaN NaN NaN NaN NaN NaN NaN
Pacific/Auckland            0.0  NaN NaN NaN NaN NaN NaN NaN
Pacific/Honolulu            0.0  NaN NaN NaN NaN NaN NaN NaN

[97 rows x 32 columns]

In [9]:
frame[tz.value_counts()

TypeError: unhashable type: 'list'